// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Application.Batch.Core.Domain.Common;

namespace Bob.Models;

public partial class Address : Entity
{

    public int CustomerId { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string ZipCode { get; set; }

    public virtual Customer Customer { get; set; }
}