// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Application.Batch.Core.Domain.Common;

namespace Bob.Models;

public partial class Customer : Entity
{
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string SocialSecurityNumber { get; set; }

    public bool IsRevoked { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();
}